In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([4, 5])
len_data, ndim = a.shape
len_data

2

In [61]:
# 特徴量関数
b = np.array([a**3, a**2, a, np.ones((len_data, ndim))])
b[:, 0, :]
b

array([[[  1.,   8.,  27.],
        [ 64., 125., 216.]],

       [[  1.,   4.,   9.],
        [ 16.,  25.,  36.]],

       [[  1.,   2.,   3.],
        [  4.,   5.,   6.]],

       [[  1.,   1.,   1.],
        [  1.,   1.,   1.]]])

In [30]:
np.dot(b[0],  b[0].T)

array([[  794.,  6896.],
       [ 6896., 66377.]])

In [13]:
b[:, 0, :] * y[0]

array([[  4.,  32., 108.],
       [  4.,  16.,  36.],
       [  4.,   8.,  12.],
       [  4.,   4.,   4.]])

In [39]:
c = np.array([np.dot(b[:, i, :], b[:, i, :].T) for i in range(len_data)])
c

array([[[7.9400e+02, 2.7600e+02, 9.8000e+01, 3.6000e+01],
        [2.7600e+02, 9.8000e+01, 3.6000e+01, 1.4000e+01],
        [9.8000e+01, 3.6000e+01, 1.4000e+01, 6.0000e+00],
        [3.6000e+01, 1.4000e+01, 6.0000e+00, 3.0000e+00]],

       [[6.6377e+04, 1.1925e+04, 2.1770e+03, 4.0500e+02],
        [1.1925e+04, 2.1770e+03, 4.0500e+02, 7.7000e+01],
        [2.1770e+03, 4.0500e+02, 7.7000e+01, 1.5000e+01],
        [4.0500e+02, 7.7000e+01, 1.5000e+01, 3.0000e+00]]])

In [42]:
c.sum(axis=0)

array([[6.7171e+04, 1.2201e+04, 2.2750e+03, 4.4100e+02],
       [1.2201e+04, 2.2750e+03, 4.4100e+02, 9.1000e+01],
       [2.2750e+03, 4.4100e+02, 9.1000e+01, 2.1000e+01],
       [4.4100e+02, 9.1000e+01, 2.1000e+01, 6.0000e+00]])

In [43]:
sigma_y = 1.0
sigma_w = 1.0

In [48]:
inv_sigma = sigma_y**(-2) * c.sum(axis=0) + sigma_w**(-2) * np.eye(4)

In [49]:
sigma = np.linalg.inv(inv_sigma)
sigma

array([[ 0.00180498, -0.01436289,  0.02395271,  0.00114598],
       [-0.01436289,  0.1226412 , -0.23897408,  0.02744884],
       [ 0.02395271, -0.23897408,  0.63257481, -0.30008186],
       [ 0.00114598,  0.02744884, -0.30008186,  0.61407133]])

In [69]:
# y_nとphi_(x_n)の積を計算
v = np.array([y[i] * b[:, i, :] for i in range(len_data)])
# 事後分布の平均パラメータの更新
mu = np.dot(sigma, sigma_y**(-2) * (v.sum(axis=0)))
mu

array([[-0.03649191, -0.03854531,  0.05825453],
       [ 0.15994543,  0.21688404, -0.3624884 ],
       [ 0.16791269,  0.21581446,  0.70481855],
       [ 1.00167609,  0.24713311,  0.2135724 ]])